KODBURG/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Welcome.as_view(), name="welcome"),
    path('enter/', views.Enter.as_view(), name="enter"),
    path('profile/', views.update_profile, name="profile"),
    path('exit/', views.LogoutView.as_view(template_name="KODBURG/welcomeBack.html"), name="exit"),
    path('email_confirm/<str:email_hash>/<str:username>/', views.emailConfirm, name="email_confirm"),
    path('email_send_confirm/<str:email>/', views.email_send_confirm, name="email_send_confirm"),
    path('password_change/<str:password_hash>/<str:username>/', views.passwordChange, name="password_change"),
    path('password_change_confirm/<str:email>/', views.password_send_change, name="password_change_confirm"),
    path('lost_user/', views.search_lost_user, name="search_lost_user"),
    
    path('main_blog/', views.main_blog, name="main_blog"),
    path('main_project/', views.main_project, name="main_project"),
    path('main_blog/<int:id>/details/', views.blog_details, name = "blog_details"),
    path('main_project/<int:id>/details/', views.project_details, name = "project_details"),
    path('main/my_blog/', views.my_blog, name="my_blog"),
    path("main/friends", views.My_friends.as_view(), name="my_friends"),
    path("main/my_notice", views.My_notice.as_view(), name="my_notice"),
    path('main/my_blog/create_blog/', views.add_blog, name="add_blog"),
    path('main/my_blog/<str:username>/<int:pk>/update',
         views.Update_blog.as_view(), name="update_blog"),
    path('main/my_blog/<str:username>/<int:pk>/delete',
         views.Delete_blog.as_view(), name="delete_blog"),
    path('main/my_projects/', views.my_project, name="my_projects"),
    path('main/descriptions/', views.My_descriptions.as_view(), name="my_descriptions"),
    path('main/my_projects/create_project/',
         views.add_project, name="add_project"),
    path('main/my_projects/<str:username>/<int:pk>/update',
         views.Update_project.as_view(), name="update_project"),
    path('main/my_projects/<str:username>/<int:pk>/delete',
         views.Delete_project.as_view(), name="delete_project"),
    path('main/search', views.Search.as_view(), name="search"),
    path('main/<str:username>/<int:userID>/viewing/',
         views.other_user, name="other_user"),
    path('main/messager', views.messager, name="messager"),
    
    path("main/chat/create/<str:user_from>/<str:user_to>/", views.create_chat, name="create_chat"),
    path("main/chat/<int:user_from>/<int:user_to>/", views.chat , name="chat"),
]

main/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('KODBURG.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

KODBURG/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    image = models.ImageField(upload_to="User/photo", default="kodburg/enter.png")
    bio = models.TextField(verbose_name="Биография")
    friends = models.ManyToManyField("User", blank=True, verbose_name="Друзья")
    notice = models.ManyToManyField("Notice", blank=True, verbose_name="Уведомления")
    descriptions = models.ManyToManyField("User", blank=True, related_name="Descriptions", verbose_name="Подписки")
    chats = models.ManyToManyField("Room", blank=True, verbose_name="Переписки")
    connections = models.ManyToManyField("Requests", blank=True, related_name="connections", verbose_name="Связи")
    new_messages = models.BooleanField(blank=True, default=False)
    email_hash = models.CharField(max_length=10000, null=True, blank=True, default="")
    email_confirm = models.BooleanField(blank=True, default=False)
    password_hash = models.CharField(max_length=10000, null=True, blank=True, default="")



class Blog_list(models.Model):
    title = models.CharField(max_length=255)
    img = models.ImageField(upload_to="User/blog",
                            default="User/blog/enter.png")
    text = models.TextField()
    date = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, blank=True, related_name="like_blog")
    dislike = models.ManyToManyField(User, blank=True, related_name="dislike_blog")
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


class Project_list(models.Model):
    title = models.CharField(max_length=255)
    img = models.ImageField(upload_to="User/projects/img",
                            default="User/blog/enter.png")
    file = models.FileField(upload_to="User/projects/files")
    text = models.TextField()
    date = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, blank=True, related_name="like_project")
    dislike = models.ManyToManyField(User, blank=True, related_name="dislike_project")
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return self.title


class Notice(models.Model):
    usernameFrom = models.ForeignKey(
        User, related_name="usernameFrom", on_delete=models.CASCADE, null=True, blank=True)
    usernameTo = models.ForeignKey(
        User, related_name="usernameTo", on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to="User/photo", default="img/enter.png")
    text = models.TextField()
    read = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.usernameFrom.username}_{self.usernameTo.username}"




class Friends_request(models.Model):
    from_user = models.ForeignKey(
        User, related_name="from_user", on_delete=models.CASCADE)
    to_user = models.ForeignKey(
        User, related_name="to_user", on_delete=models.CASCADE)

    
    def __str__(self):
        return f"{self.from_user.username}_{self.to_user.username}"
    

class Comment_blog(models.Model):
    blog = models.ForeignKey(Blog_list, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to="other_img", default="img/enter.png")
    text = models.TextField()
    publishing = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now=True)


class Comment_project(models.Model):
    project = models.ForeignKey(Project_list, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to="other_img", default="img/enter.png")
    text = models.TextField()
    publishing = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now=True)

class Room(models.Model):
    title = models.CharField(max_length=255)
    time_create = models.DateTimeField(auto_now=True)
    mes = models.ManyToManyField("Messages", related_name="mes", blank=True)
    def __str__(self) -> str:
        return self.title

class Messages(models.Model):
    user_from = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name="user_from")
    message = models.CharField(max_length=255)
    viewed = models.BooleanField(default=False)
    time_send = models.DateTimeField(auto_now=True)
    room = models.ForeignKey("Room", on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.message
    

class Requests(models.Model):
    user_from = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="user_fromReq")
    user_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="user_toReq")
    
    def __str__(self):
        return f"{self.user_from.username}.web.{self.user_to.username}"
    



class Post(models.Model):
    title = models.TextField()
    image = models.ImageField(upload_to="kodburg/")
    
    def __str__(self) -> str:
        return self.title
    

KODBURG/forms.py
from .models import *
from django.forms import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class UserCreateForm(UserCreationForm):
    username = CharField(
        label="Введите свой nickname",
        max_length=255,
        widget=TextInput(
            attrs={
                "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                "placeholder": "nickname",
            }
        ),
    )

    email = CharField(
        label="Введите свою электронную почту",
        max_length=255,
        widget=(
            TextInput(
                attrs={
                    "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                    "placeholder": "email",
                }
            )
        ),
    )

    password1 = CharField(
        label="Введите пароль",
        max_length=255,
        widget=TextInput(
            attrs={
                "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                "placeholder": "password",
                "type": "password",
            }
        ),
    )

    password2 = CharField(
        label="Повторите пароль",
        max_length=255,
        widget=TextInput(
            attrs={
                "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                "placeholder": "password",
                "type": "password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"autofocus": False})
        self.fields["password1"].widget.attrs.update({"autofocus": False})
        self.fields["password2"].widget.attrs.update({"autofocus": False})
        self.fields["email"].widget.attrs.update({"autofocus": False})

    def clean(self):
        cleaned_data = super(UserCreateForm, self).clean()
        username = cleaned_data.get("username")
        num = [f"{i}" for i in range(9)]
        sim = ["@", "+", "-", "_"] + num
        for i in username:
            if not i.isalpha() and i not in sim:
                self.add_error(
                    "username",
                    "Введите правильное имя пользователя. Оно может содержать только буквы, цифры и знаки @/+/-/_.",
                )
                break
        return cleaned_data


class UserLoginForm(AuthenticationForm):
    username = CharField(
        label="Введите свой nickname",
        max_length=255,
        widget=TextInput(
            attrs={
                "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                "placeholder": "nickname",
            }
        ),
    )

    password = CharField(
        label="Введите пароль",
        max_length=255,
        widget=TextInput(
            attrs={
                "class": "input-class col-xxl-3 col-lg-5 col-md-8 col-sm-12",
                "placeholder": "password",
                "type": "password",
            }
        ),
    )

    class Meta:
        model = User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "image", "bio"]
        widgets = {
            "username": TextInput(
                attrs={"class": "input-class col-12", "placeholder": "nickname"}
            ),
            "email": TextInput(
                attrs={
                    "class": "input-class col-12 email",
                    "placeholder": "email",
                    "type": "email",
                }
            ),
            "first_name": TextInput(
                attrs={
                    "class": "input-class col-12",
                    "placeholder": "Как вас зовут?",
                }
            ),
            "last_name": TextInput(
                attrs={
                    "class": "input-class col-12",
                    "placeholder": "Можно узнать вашу фамилию?",
                }
            ),
            "image": FileInput(
                attrs={
                    "class": "input-class col-12",
                }
            ),
            "bio": Textarea(
                attrs={
                    "class": "input-class text col-12",
                    "style": "text-align: start!important, overflow: hidden;",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["bio"].required = False

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        username = cleaned_data.get("username")
        num = [f"{i}" for i in range(0, 10)]
        sim = ["@", "+", "-", "_"] + num
        for i in username:
            if not i.isalpha() and i not in sim:
                self.add_error(
                    "username",
                    "Введите правильное имя пользователя. Оно может содержать только буквы, цифры и знаки @/+/-/_.",
                )
                break
        return cleaned_data


class UserPasswordForm(ModelForm):
    class Meta:
        model = User
        fields = ["password"]
        widgets = {
            "password": PasswordInput(
                attrs={
                    "class": "input-class col-12",
                    "placeholder": "Введите новый пароль",
                }
            )
        }


class UserLostForm(ModelForm):
    username = CharField(
        label="Введите свой username",
        max_length=255,
        widget=TextInput(
            attrs={"class": "input-class col-12", "placeholder": "username"}
        ),
    )
    email = CharField(
        label="Введите свой email",
        max_length=255,
        widget=EmailInput(
            attrs={"class": "input-class col-12", "placeholder": "email"}
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].required = False
        self.fields["email"].required = False
    


class Blog_form(ModelForm):
    class Meta:
        model = Blog_list
        fields = ["title", "text", "img", "username"]
        widgets = {
            "title": TextInput(
                attrs={
                    "class": "col-12 col-lg-7 h-100",
                    "placeholder": "Название поста",
                }
            ),
            "text": Textarea(
                attrs={
                    "class": "col-12",
                }
            ),
            "img": FileInput(attrs={"style": "color: black!important"}),
        }


class Project_form(ModelForm):
    class Meta:
        model = Project_list
        fields = ["title", "text", "img", "file", "username"]
        widgets = {
            "title": TextInput(
                attrs={
                    "class": "col-12 col-lg-7 h-100",
                    "placeholder": "Название поста",
                }
            ),
            "text": Textarea(
                attrs={
                    "style": "overflow: hidden;",
                    "class": "col-12",
                }
            ),
            "img": FileInput(attrs={"style": "color: black!important"}),
            "file": FileInput(
                attrs={"style": "color: black!important", "accept": ".rar, .zip"}
            ),
        }


class Friend_form(ModelForm):
    class Meta:
        model = Notice
        fields = ["usernameFrom", "usernameTo", "image", "text"]


class Comments_to_blog(ModelForm):
    class Meta:
        model = Comment_blog
        fields = ["blog", "author", "text", "image"]
        widgets = {
            "text": Textarea(attrs={"class": "col-12", "style": "height: 5vh"}),
            "image": FileInput(
                attrs={
                    "class": "input-class col-12",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["image"].required = False


class Comments_to_projects(ModelForm):
    class Meta:
        model = Comment_project
        fields = ["project", "author", "text", "image"]
        widgets = {
            "text": Textarea(attrs={"class": "col-12", "style": "height: 5vh"}),
            "image": FileInput(
                attrs={
                    "class": "input-class col-12",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["image"].required = False

KODBURG/templates/KODBURG/blog_details.html
{% extends 'KODBURG/shablon_main.html' %}

{% block title %}{{i.title}}{% endblock title %}

{% block content %}

<div class="row justify-content-center align-items-center list g-2" id="{{i.title}}">
      <div class="row justify-content-center align-items-center">
        <h3 class="col-12 text-center">{{i.title}}</h3>
        {% if i.img.url != "/media/User/blog/enter.png" %}
        <img src="{{i.img.url}}" alt="" />
        {% endif %}
        <div class="col-12 p-3" style="word-break: break-all;">{{i.text}}</div>

        <h6 class="col-12">{{i.date}}</h6>
        <a
          class="a_black text-decoration-underline"
          href="{% url 'other_user' i.username.username i.username.id %}"
          role="button"
          >{{i.username.username}}</a
        >
        <div class="row justify-content-start align-items-center g-2">
        {% if user != i.username %}
          {% if user in i.like.all %}
            <a id="{{i.id}}" name="blog" class="btn btn-danger col-2 like" role="button">{{i.like.count}}</a>
          {% else %}
            <a id="{{i.id}}" name="blog" class="btn btn-outline-danger col-2 a_like like" role="button">{{i.like.count}}</a>
          {% endif %}
            {% if user in i.dislike.all %}
              <a id="{{i.id}}" name="blog" class="btn btn-dark col-2" role="button dislike">{{i.dislike.count}}</a>
            {% else %}
              <a id="{{i.id}}" name="blog" class="btn btn-outline-dark col-2 a_dislike dislike" role="button">{{i.dislike.count}}</a>
          {% endif %}
        {% else %}
        <div class="row justify-content-start align-items-center g-2">
          <div id="" class="btn btn-danger col-2" role="button">{{i.like.count}}</div>
          <div id="" class="btn btn-dark col-2" role="button">{{i.dislike.count}}</div>
        </div>
        {% endif %}
      </div>
      </div>
      <form
        method="POST"
        class="row justify-content-center align-items-center border-top border-bottom m-3 g-2"
        enctype="multipart/form-data"
      >
        <h4 class="col-12 align-self-center">Оставьте свой комментарий</h4>
        {% csrf_token %}
        <fieldset>
          <select
            name="blog"
            class="vTextField"
            maxlength="255"
            required=""
            style="visibility: hidden; display: none"
            id="id_blog"
          >
            <option value="{{i.id}}">{{i}}</option>
          </select>

          {{form_blog.image}} {{form_blog.text}}
          <div class="row justify-content-center align-items-center g-2 m-2">
            <button type="submit" class="btn btn-success col-12">
              Отправить
            </button>
          </div>
        </fieldset>
      </form>
      <div class="row justify-content-center align-items-center g-2">
        {% for item in comments_blog %} 
        <div
          class="row justify-content-center align-items-center comm border-bottom g-2"
        >
          <div
            class="row justify-content-center align-items-center col-3 m-2 g-2"
          >
            <a
              class="row col-12"
              href="{% url 'other_user' item.author.username item.author.id %}"
            >
              <img src="{{item.author.image.url}}" alt="" class="col rounded-circle" />
            </a>
          </div>
          <div
            class="row justify-content-center align-items-center col m-0 p-0"
          >
            <div class="row align-self-center g-2">
              <a
                class="col text-decoration-underline a_black align-self-center"
                href="{% url 'other_user' item.author.username item.author.id %}"
                >{{item.author.username}}</a
              >
              <div class="col">{{item.date}}</div>
            </div>
            <div class="row justify-content-center align-items-center m-3">
              <div class="col">{{item.text}}</div>
            </div>
          </div>
          {% if item.image != "img/enter.png" %}
          <div class="row justify-content-center align-items-center border g-2">
            <img src="{{item.image.url}}" alt="" />
          </div>
          {% endif %}
        </div>
        
        
        {% empty %}
        <div class="row justify-content-center align-items-center g-2 text-center">
          <p class="col">Здесь пока нет комментариев</p>
        </div>
        {% endfor %}
      </div>
    </div>

{% endblock content %}

KODBURG/templates/KODBURG/change_blog.html
{% extends 'KODBURG/shablon_main.html' %} 

{% block title %}Изменение поста {{form.title.value}}{% endblock title %} 

{% block content %} 

{% if user.pk == form.username.value %}
<div class="row justify-content-center align-items-center g-2 text-center">
  <h3>Форма изменения записи</h3>
</div>

<form
  action=""
  method="post"
  enctype="multipart/form-data"
  class="list justify-content-start row"
>
  {% csrf_token %} {% if error %}
  <div class="alert alert-danger" role="alert">{{error}}</div>

  {% endif %}
  <fieldset class="justify-content-start row">
    <div class="row justify-content-start align-items-center p-3">
      <label for="">Введите название статьи</label>
      {{form.title}}
    </div>

    <div class="row justify-content-start align-items-center p-3">
      <label for="">Загрузите фото для статьи:</label>
      {{form.img}}
    </div>

    <div class="row justify-content-start align-items-center p-3">
      <label for="">Введите текст статьи</label>
      {{form.text}}
    </div>
    <select
      type="text"
      name="username"
      maxlength="255"
      id="id_username"
      style="transform: scale(0); display: none"
    >
    <option value="{{user.id}}">{{user}}</option>
    </select>
  </fieldset>
  <div class="row justify-content-start align-items-center p-3">
    <button type="submit" class="btn btn-primary">Подтвердить изменения</button>
  </div>
</form>
{% else %}
<div class="row justify-content-center align-items-center text-center">
  <h5 class="col">
    Пытаться изменить чужой пост и выставить на посмешище другого человека - это
    так низко, ну просто фу!<br />
    Для таких как ты приготовлен отдельный котел в аду!<br />
    А теперь пошел прочь!<br />
  </h5>
</div>
{% endif %} 
{% endblock content %}

KODBURG/templates/KODBURG/chat.html
{% extends 'KODBURG/shablon_main.html' %}
{% load static %}
{% block title %}
{% if User1 == user %}
{{User2.username}}
{% else %}
{{User1.username}}

{% endif %}
{% endblock title %}
{% block content %}

{% if user.username == User1.username or user.username == User2.username %}

{{room_name|json_script:"room-name"}}
{{room_id|json_script:"room-id"}}
{{user.username|json_script:"user_from"}}

{{user.image.url|json_script:"image"}}
{{user.pk|json_script:"my_id"}}

{% if User1 == user %}
  {{User2.id|json_script:"User_id"}}
  {{User2.username|json_script:"user_to"}}
  {% else %}
  {{User1.id|json_script:"User_id"}}
  {{User1.username|json_script:"user_to"}}

{% endif %}
<div class="row align-items-start flex-column g-2 p-0 list chat_log">

    {% for i in messages %}

      {% for key, value in date.items %}
        {% if value == i %}
          <div class="row justify-content-center align-items-center text-center g-2">
            <div class="col">{{i.time_send.date}}</div>
          </div>
        {% endif %}
      {% endfor %}

      {% if i.user_from == user %}
        {% if i.viewed %}
        <div class="msg_from col-12 read">
        {% else %}
        <div class="msg_from col-12">
        {% endif %}
          <div class="col-10 row align-self-start justify-content-end">
              <div class="row col-12 justify-content-end text-end">
                <div class="col">{{i.time_send.time}}</div>
                <div class="col text-decoration-underline">{{user.username}}</div>
              </div>
            <div class="col-12 message">{{i.message}}</div>
          </div>
          <div class="img">
            <img src="{{user.image.url}}" class="col" alt="">
          </div>
        </div>
      {% else %}
        {% if i.viewed %}
          <div class="msg_to col-12 read">
        {% else %}
          {% if i == non_viewed %}
            <div class="col-12 text-center">Новые сообщения!</div>
            <div class="msg_to col-12 first_message non_read">
          {% else %}
            <div class="msg_to col-12 non_read">
          {% endif %}
          <script class="non_viewed" type="application/json">{{i.pk}}</script>
        {% endif %}
            <div class="col-10 row align-self-start">
              <a class="col text-decoration-underline a_black a_link" href="{% url 'other_user' i.user_from.username i.user_from.id %}">{{i.user_from.username}}</a>
              <div class="col">{{i.time_send.time}}</div>
              <div class="col-12 message">{{i.message}}</div>
            </div>
            <div class="img">
              <img src="{{i.user_from.image.url}}" class="col" alt="">
            </div>
          </div>
      {% endif %}
    {% empty %}
      <h4 class='col-12 text-center no_messages'>Напишите первое сообщение!</h4>
    {% endfor %}

</div>
<div class="row justify-content-center align-items-center g-2">
  <textarea class="form-control" name="" id="chat_message" rows="1"></textarea>
</div>
<div class="row justify-content-center align-items-center g-2">
    <input name="" id="chat_button" class="btn btn-success" type="button" value="Отправить сообщение">
</div>



<script src={% static 'KODBURG/js/chat.js' %}></script>
{% else %}
<div class="row justify-content-center align-items-center g-2">
  <h3 class="col-12">Знаете, а читать чужие сообщения неприлично, {{user.username}}</h3>
</div>

{% endif %}

{% endblock content %}

KODBURG/templates/KODBURG/create_blog.html
{% extends 'KODBURG/shablon_main.html' %}

{% block title %}Создание поста{% endblock title %}
{% block content %}
<div class="row justify-content-center align-items-center g-2 text-center">
    <h3>Форма создания поста</h3>
</div>

<form action="" method="post" enctype="multipart/form-data",  class="list justify-content-start row" >
    {% csrf_token %}
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
    </div>
    
    {% endif %}
  <fieldset class="justify-content-start row">
    <div class="row justify-content-start align-items-center p-3">
        <label for="">Введите название статьи</label>
        {{form.title}}
    </div>
    
        <div class="row justify-content-start align-items-center p-3">
            <label for="">Загрузите фото для статьи</label>
            {{form.img}}
        </div>
    
    <div class="row justify-content-start align-items-center p-3">
        <label for="">Введите текст статьи</label>
        {{form.text}}
    </div>
    <div class="row justify-content-start align-items-center p-3">
        <button type="submit" class="btn btn-primary">Создать запись</button>
    </div>
</fieldset> 
</form>

{% endblock content %}

KODBURG/templates/KODBURG/email_confirm.html
{% extends 'KODBURG/shablon.html' %}

{% block title %}Пожтверждение email{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center g-2 text-center">
    <h4 class="col">
        Почта {{user.email}} подтверждена!<br>
        Можете закрыть эту страницу.
    </h4>
</div>
</div>

{% endblock content %}

KODBURG/templates/KODBURG/my_friends.html
{% extends 'KODBURG/shablon_main_notice.html' %}
{% block title %}Друзья {{user.username}}{% endblock title %}

{% block content %}
<div class="row justify-content-center align-items-center g-2 friends">


{% for i in user.friends.all %}
  <a
      href="{% url 'other_user' i.username i.id %}"
      class="row col-12 text-center user-friend align-items-center m-0 p-0 flex-row flex-nowrap a_black h-100"
    >
    <img src="{{i.image.url}}" class="col-1" alt="">
    <div class="col">{{i.username}}</div>
  </a>


{% empty %}
  <div class="row justify-content-center text-center align-items-center g-2 no_friends">
    <div class="col">У вас пока нет уведомлений</div>
  </div> 
{% endfor %} 
</div>


{% endblock content %}

KODBURG/templates/KODBURG/password_change.html
{% extends 'KODBURG/shablon.html' %}

{% block title %}Форма смены пароля{% endblock title %}

{% block content %}
<div class="container">
    <form method="POST" class="row justify-content-center align-items-center g-2 text-center">
    {% csrf_token %} 
        {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{error}}
                    </div>
                {% endif %}
    {% for i in form %}
        

        <label
        for="{{i.id_for_label}}"
        class="from-label col-12"
        style="color: black !important"
        >{{i.label}}</label
        >
        {{i}}
    
    {% endfor %}
    <button type="submit" class="btn btn-primary">Подтвердить изменения</button>
    </form>
</div>

{% endblock content %}

KODBURG/templates/KODBURG/reach.html
{% extends 'KODBURG/shablon_main.html' %} 
{% block title %}Поиск{% endblock title %} 

{% block content %}
<div class="row justify-content-center align-items-center g-2 list">
  <form action="" method="post" class="row justify-content-between">
    <h5 class="col">Введите ник пользователя или название группы</h5>
    <input type="text" class="p-2" style="margin-bottom: 1em !important" />
    <button type="submit" class="btn btn-primary">Найти</button>
  </form>
  {% comment %} <div class="row justify-content-center align-items-center g-2">
    <h4 class="col-12">Существующие группы</h4>
  </div> {% endcomment %}
  <div class="row justify-content-center align-items-center g-2">
    <h4 class="col-12">Существующие пользователи:</h4>
    <div class="col-12 row justify-content-around">
      {% for i in object_list %}
      {% if i.username != user.username%} 
      <a
        class="col-lg-4 col-sm-2 col-12 row user-reach  p-2"
        href="{% url 'other_user' i.username i.id %}"
      >
        <img src="{{i.image.url}}" class="col-sm-10 col-3" alt="user"/>
        <div class="col-sm-12 col username p-0">{{i.username}}</div>
      </a>
      {% endif %} {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}